# TODO: explain it
name: torsney-cookbook

# TODO: explain it
# subdomain: sample

# TODO: explain it
# domains: [www.example.com, example.com]

# TODO: explain it
locales: [en]

# TODO: explain it
seo_title: torsney-cookbook
meta_keywords: "some meta keywords"
meta_description: "some meta description"